version: '3.7'

services:
  cluster:
    container_name: cluster-service-web-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5000:5000'
    env_file:
      - .env
